name: reasoning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - betty-ml==0.2.1
    - datasets==3.0.2
    - huggingface-hub==0.30.2
    - json5==0.9.6
    - numpy==1.26.4
    - pillow==11.2.1
    - scikit-image==0.23.2
    - scipy==1.13.1
    - tokenizers==0.21.1
    - torch==2.5.1
    - torchvision==0.20.1
    - transformers==4.49.0
    - wandb==0.18.5
    - accelerate
    - einops
    - timm
    - rich